[phases.setup]
nixPkgs = ["nodejs_24", "bun"]

[phases.install]
cmds = [
  "bun install --frozen-lockfile"
]

[phases.build]
cmds = ["bun run build"]

[phases.prune]
cmds = [
  "bun install --production"
]

[start]
cmd = "bun run start:migrate"
