name: Build and Test

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "The environment to deploy to"
        required: false
        default: "development"

env:
  APP_ENV: "${{ secrets.APP_ENV }}"
  GOOGLE_CLIENT_ID: "${{ secrets.GOOGLE_CLIENT_ID }}"
  GOOGLE_CLIENT_SECRET: "${{ secrets.GOOGLE_CLIENT_SECRET }}"
  MONGODB_URI: "${{ secrets.MONGODB_URI }}"
  NEXTAUTH_SECRET: "${{ secrets.NEXTAUTH_SECRET }}"
  DISCORD_CLIENT_ID: "${{ secrets.DISCORD_CLIENT_ID }}"
  DISCORD_CLIENT_SECRET: "${{ secrets.DISCORD_CLIENT_SECRET }}"
  SOCKET_IO_ADMIN_USERNAME: "${{ secrets.SOCKET_IO_ADMIN_USERNAME }}"
  SOCKET_IO_ADMIN_PASSWORD: "${{ secrets.SOCKET_IO_ADMIN_PASSWORD }}"
  WEBSITE_URL: "${{ secrets.WEBSITE_URL }}"
  NEXT_PUBLIC_THE_GENIUS_ENV: "${{ secrets.NEXT_PUBLIC_THE_GENIUS_ENV }}"
  NEXT_PUBLIC_PARTYKIT_HOST: "${{ secrets.NEXT_PUBLIC_PARTYKIT_HOST }}"
  NEXT_PUBLIC_POSTHOG_KEY: "${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}"
  NEXT_PUBLIC_POSTHOG_HOST: "${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Run Linter
        run: bun run lint

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Run TypeScript check
        run: bun run tsc

  test:
    name: Test
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Run unit tests
        run: bun run test:unit

  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Build application
        run: bun run build
