name: CI

# Only run if pushes to staging and changed files are relevant for the app or E2E tests
on:
  push:
    branches:
      - staging
    paths:
      - "src/**"
      - "e2e/**"
      - "prisma/**"
      - "playwright.config.ts"

jobs:
  checks:
    name: Run Checks
    uses: ./.github/workflows/build_and_test.yml
    with:
      environment: development
    secrets: inherit
