name: CI

# Only run if pushes to staging and changed files are in the src directory
on:
  push:
    branches:
      - staging
    paths:
      - "src/**"

jobs:
  checks:
    name: Run Checks
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
