name: Deploy Template

on:
  workflow_call:
    inputs:
      environmentName:
        description: The name of the environment to deploy to.
        required: true
        type: string
      url:
        description: The URL to deploy to.
        required: true
        type: string

env:
  APP_ENV: "${{ secrets.APP_ENV }}"
  GOOGLE_CLIENT_ID: "${{ secrets.GOOGLE_CLIENT_ID }}"
  GOOGLE_CLIENT_SECRET: "${{ secrets.GOOGLE_CLIENT_SECRET }}"
  MONGODB_URI: "${{ secrets.MONGODB_URI }}"
  NEXTAUTH_SECRET: "${{ secrets.NEXTAUTH_SECRET }}"
  DISCORD_CLIENT_ID: "${{ secrets.DISCORD_CLIENT_ID }}"
  DISCORD_CLIENT_SECRET: "${{ secrets.DISCORD_CLIENT_SECRET }}"
  SOCKET_IO_ADMIN_USERNAME: "${{ secrets.SOCKET_IO_ADMIN_USERNAME }}"
  SOCKET_IO_ADMIN_PASSWORD: "${{ secrets.SOCKET_IO_ADMIN_PASSWORD }}"
  WEBSITE_URL: "${{ secrets.WEBSITE_URL }}"
  NEXT_PUBLIC_THE_GENIUS_ENV: "${{ secrets.NEXT_PUBLIC_THE_GENIUS_ENV }}"
  NEXT_PUBLIC_PARTYKIT_HOST: "${{ secrets.NEXT_PUBLIC_PARTYKIT_HOST }}"
  NEXT_PUBLIC_POSTHOG_KEY: "${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}"
  NEXT_PUBLIC_POSTHOG_HOST: "${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    environment:
      name: ${{ inputs.environmentName }}
      url: ${{ inputs.url }}
    steps:
      #   - name: Download artifact
      #     uses: actions/download-artifact@v4
      #     with:
      #       name: ${{ inputs.artifactName }}
      #       path: ./buildArtifact

      # Steps to deploy the code go here.
      #   - name: Install Railway
      #     run: npm i -g @railway/cli

      - name: Deploy to ${{ inputs.environmentName }}
        run: railway up --service the-genius --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
