name: Deploy Template

on:
  workflow_call:
    inputs:
      environmentName:
        description: The name of the environment to deploy to.
        required: true
        type: string
      url:
        description: The URL to deploy to.
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    environment:
      name: ${{ inputs.environmentName }}
      url: ${{ inputs.url }}
    steps:
      #   - name: Download artifact
      #     uses: actions/download-artifact@v4
      #     with:
      #       name: ${{ inputs.artifactName }}
      #       path: ./buildArtifact

      # Steps to deploy the code go here.
      #   - name: Install Railway
      #     run: npm i -g @railway/cli

      - name: Deploy to ${{ inputs.environmentName }}
        run: railway up --service the-genius --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
