name: Deploy Template

on:
  workflow_call:
    inputs:
      environmentName:
        description: The name of the environment to deploy to.
        required: true
        type: string
      url:
        description: The URL to deploy to.
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environmentName }}
      url: ${{ inputs.url }}
    steps:
      # - name: Download artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: ${{ inputs.artifactName }}
      #     path: ./buildArtifact

      # Steps to deploy the code go here.
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Node.js version
        id: extract_node_version
        run: echo "NODE_VERSION=$(jq -r '.engines.node' package.json)" >> $GITHUB_OUTPUT

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # - name: Install dependencies
      #   run: bun install

      # - name: Build
      #   run: bun run build

      - name: Deploy to ${{ inputs.environmentName }}
        run: bunx @railway/cli up --service the-genius --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
