name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Type of release'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
          
jobs:
  staging:
    name: Deploy to staging
    environment: 
        name: staging
        url: https://the-genius-staging.up.railway.app/
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Extract Node.js version
          id: extract_node_version
          run: echo "::set-output name=NODE_VERSION::$(jq -r '.engines.node' package.json)"

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: ${{ steps.extract_node_version.outputs.NODE_VERSION }}

        - name: Install dependencies
          run: npm ci

        - name: Build
          run: npm run build

        - name: Install Railway
          run: npm i -g @railway/cli

        - name: Deploy to staging
          run: railway up
          env:
            RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  production:
    if: github.event.inputs.releaseType == 'production'
    name: Deploy to production
    environment: 
        name: staging
        url: https://beta.the-genius.de/
    needs: [staging]

    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Extract Node.js version
          id: extract_node_version
          run: echo "::set-output name=NODE_VERSION::$(jq -r '.engines.node' package.json)"

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: ${{ steps.extract_node_version.outputs.NODE_VERSION }}

        - name: Install dependencies
          run: npm ci

        - name: Build
          run: npm run build

        - name: Install Railway
          run: npm i -g @railway/cli

        - name: Deploy to production
          run: railway up
          env:
            RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}