name: Deploy code

on:
  push:
    branches: production

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-version-bumped:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if version is bumped
        id: check_version
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "Current version: $CURRENT_VERSION"
          if git tag --list | grep -q $CURRENT_VERSION; then
            echo "Version $CURRENT_VERSION already exists as a tag. Please bump the version in package.json."
            exit 1
          fi
          echo "APP_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT

  build-and-test:
    needs: check-version-bumped
    uses: ./.github/workflows/build_and_test.yml
    with:
      environment: production
    secrets: inherit # Pass secrets to the build workflow, if necessary.

  deploy-to-staging:
    # Only run this deploy job after the build-and-test job completes successfully.
    needs: build-and-test
    uses: ./.github/workflows/deploy_railway_template.yml
    with:
      environmentName: staging
      url: https://the-genius-staging.up.railway.app/

    secrets: inherit

  deploy-to-production:
    # Only run this deploy job after the deploy-to-staging job completes successfully.
    needs: deploy-to-staging
    uses: ./.github/workflows/deploy_railway_template.yml
    with:
      environmentName: production
      url: https://beta.the-genius.de/

    secrets: inherit

  create-tag:
    needs: deploy-to-production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          TAG_NAME="v$CURRENT_VERSION"
          echo "Current version: $CURRENT_VERSION"
          git tag -a $TAG_NAME -m "Release $TAG_NAME"
          git push origin $TAG_NAME
