name: ESLint

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - staging
    types:
      - closed

jobs:
  eslint:
    name: Lint code base
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.15.1"

      - name: Install dependencies
        run: npm ci

      - name: List environment variables
        run: echo ${{ env.NEXTAUTH_SECRET }}

      - name: Run Linter
        run: npm run lint
